Allows a model param to be found using findContextOrMain
novius/noviusos_controller_front_enhancer pull request #3
Opened 2017-04-21 13:20 UTC by Seb-C

2017-04-21 13:31 UTC, Meroje requested changes

2017-04-21 13:31 UTC, Meroje commented on classes/controller/front/application/enhancer.ctrl.php
> +        $context       = $this->main_controller->getPage()->page_context;
`$this->main_controller->getContext()`

2017-04-21 13:31 UTC, Meroje commented on classes/controller/front/application/enhancer.ctrl.php
> +            $items = $model::findContextOrMain($context, array('where' => $where));
could use compact but that's my OCD

2017-04-21 13:38 UTC, Meroje approved these changes

2017-04-24 07:17 UTC, jguyomard commented on classes/controller/front/application/enhancer.ctrl.php
> +            if (get_class($query) != 'Nos\Orm\Query') {
i think using `instanceof` or `is_a()` is better here, to allow overriding

2017-04-24 07:40 UTC, merged